; Super Mario Bros. 3 Full Disassembly by Southbird 2012
; For more info, see http://www.sonicepoch.com/sm3mix/
;
; PLEASE INCLUDE A CREDIT TO THE SOUTHBIRD DISASSEMBLY
; AND THE ABOVE LINK SOMEWHERE IN YOUR WORKS :)
;
; Original disassembler source generated by DCC6502 version v1.4
; (With labels, comments, and some syntax corrections for nesasm by Southbird)
; For more info about DCC6502, e-mail veilleux@ameth.org
;
; This source file last updated: 2012-03-25 13:37:28.828970596 -0500
; Distribution package date: Fri Apr  6 23:46:16 UTC 2012
;---------------------------------------------------------------------------

    ; Ending Sprite list continued from PRG024 ...

    .byte           $01, $28
    .byte $4F, $B7, $01, $20
    .byte $57, $B5, $01, $18
    .byte $6F, $01, $00, $D8
    .byte $6F, $01, $40, $E0
    .byte $7F, $03, $00, $D8
    .byte $7F, $03, $40, $E0
Ending2_EndPicSprites3_End

Ending2_EndPicSprites4:
    .byte $21, $81, $01, $70
    .byte $21, $83, $01, $78
    .byte $21, $85, $01, $80
    .byte $31, $87, $01, $70
    .byte $31, $89, $01, $78
    .byte $31, $41, $01, $80
    .byte $31, $43, $01, $88
    .byte $31, $45, $01, $90
    .byte $3F, $47, $01, $20
    .byte $3F, $49, $01, $28
    .byte $3F, $4B, $01, $30
    .byte $3F, $4D, $01, $38
Ending2_EndPicSprites4_End

Ending2_EndPicSprites5:
    .byte $69, $29, $00, $B0
    .byte $69, $2B, $00, $B8
    .byte $79, $01, $00, $B0
    .byte $79, $03, $00, $B8
    .byte $79, $05, $00, $C0
    .byte $A1, $53, $02, $B8
    .byte $A1, $55, $02, $C0
    .byte $B1, $57, $02, $B8
    .byte $B1, $59, $02, $C0
    .byte $99, $61, $01, $D0
    .byte $99, $63, $01, $D8
    .byte $A9, $65, $01, $D0
    .byte $A9, $67, $01, $D8
Ending2_EndPicSprites5_End

Ending2_EndPicSprites6:
    .byte $69, $19, $40, $20
    .byte $69, $27, $40, $28
    .byte $79, $1F, $40, $20
    .byte $79, $1D, $40, $28
    .byte $79, $1B, $40, $30
    .byte $61, $A7, $41, $58
    .byte $61, $AF, $41, $50
    .byte $A9, $D3, $02, $70
    .byte $A9, $D5, $02, $78
    .byte $A9, $5B, $01, $A0
    .byte $A9, $5D, $01, $A8
Ending2_EndPicSprites6_End

Ending2_EndPicSprites7:
    .byte $41, $F1, $02, $D8
    .byte $41, $F3, $02, $E0
    .byte $51, $E3, $01, $D8
    .byte $51, $E3, $41, $E0
    .byte $51, $67, $42, $C8
    .byte $61, $65, $02, $B8
    .byte $79, $65, $42, $A8
    .byte $89, $37, $40, $A8
    .byte $89, $35, $40, $B0
Ending2_EndPicSprites7_End

Ending2_EndPicSprites8:
    .byte $79, $03, $40, $28
    .byte $79, $01, $40, $30
    .byte $89, $07, $40, $28
    .byte $89, $05, $40, $30
    .byte $99, $51, $02, $50
    .byte $99, $5F, $02, $58
    .byte $90, $69, $01, $B0
    .byte $90, $6B, $01, $B8
    .byte $90, $6D, $01, $C0
    .byte $90, $6F, $01, $C8
    .byte $A0, $71, $01, $B0
    .byte $A0, $73, $01, $B8
    .byte $A0, $75, $01, $C0
    .byte $A0, $77, $01, $C8
    .byte $B0, $79, $01, $B0
    .byte $B0, $7B, $01, $B8
    .byte $B0, $7D, $01, $C0
    .byte $B0, $7F, $01, $C8
Ending2_EndPicSprites8_End


    ; Split address, parallel tables for the starting address of the end picture for each world
EndPicByWorld_H:.byte >EndPic_World1, >EndPic_World2, >EndPic_World3, >EndPic_World4
        .byte >EndPic_World5, >EndPic_World6, >EndPic_World7, >EndPic_World8

EndPicByWorld_L:.byte <EndPic_World1, <EndPic_World2, <EndPic_World3, <EndPic_World4
        .byte <EndPic_World5, <EndPic_World6, <EndPic_World7, <EndPic_World8

    ; $C0 bytes are expected to be loaded into the Ending_CmdBuffer buffer.
    ; The EndPics are mostly raw with a simple compression, specifically if
    ; bit 7 is set, that byte is duplicated once in the buffer, sans bit 7.
    ; So for example:
    ; The value $70 inserts $70 once
    ; The value $F1 inserts $71 twice

    ; End world images are 16 8x8 blocks wide by 12 8x8 blocks tall

EndPic_World1:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $BF, $3F, $00, $04, $06, $04, $00, $04, $00, $04, $06, $BF, $73              ; row 2
    .byte $73, $BF, $3F, $05, $BF, $3F, $05, $BF, $3F, $05, $BF, $73                        ; row 3
    .byte $73, $04, $0E, $04, $07, $BF, $3F, $63, $04, $00, $04, $0A, $BF, $73              ; row 4
    .byte $73, $BF, $3F, $0B, $BF, $3F, $05, $BF, $BF, $BF, $73                             ; row 5
    .byte $73, $BF, $3F, $63, $04, $62, $04, $10, $BF, $38, $44, $39, $3F, $73              ; row 6
    .byte $73, $3F, $D5, $05, $55, $BF, $3F, $38, $44, $49, $3D, $3C, $3F, $73              ; row 7
    .byte $73, $D5, $65, $63, $65, $0A, $04, $06, $1E, $06, $04, $3E, $3C, $3F, $73         ; row 8
    .byte $73, $55, $E5, $05, $E5, $55, $05, $3C, $D5, $55, $3C, $3F, $73                   ; row 9
    .byte $73, $55, $E5, $00, $04, $06, $04, $00, $48, $C4, $44, $49, $3F, $73              ; row 10
    .byte $73, $D5, $D5, $D5, $D5, $D5, $D5, $D5, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World2:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $35, $03, $04, $06, $5C, $0A, $04, $06, $04, $00, $04, $06, $65, $2F, $73    ; row 2
    .byte $73, $66, $05, $66, $05, $2F, $55, $02, $05, $E5, $65, $05, $E5, $73              ; row 3
    .byte $73, $66, $63, $5C, $00, $04, $06, $04, $66, $E6, $65, $63, $2F, $65, $73         ; row 4
    .byte $73, $0C, $05, $66, $05, $66, $66, $66, $05, $66, $3D, $66, $05, $2F, $65, $73    ; row 5
    .byte $73, $04, $07, $04, $07, $04, $1F, $5C, $63, $66, $3E, $66, $63, $66, $65, $73    ; row 6
    .byte $73, $66, $AF, $05, $66, $E6, $05, $0C, $05, $0C, $05, $66, $66, $73              ; row 7
    .byte $73, $66, $65, $2F, $63, $65, $06, $5C, $00, $66, $63, $04, $0C, $E6, $73         ; row 8
    .byte $73, $E5, $AF, $2F, $05, $66, $05, $2F, $E6, $05, $E6, $73                        ; row 9
    .byte $73, $66, $E5, $66, $2F, $10, $04, $07, $04, $06, $04, $07, $E6, $73              ; row 10
    .byte $73, $E6, $E6, $E6, $E6, $E6, $E6, $E6, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World3:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $04, $0A, $AF, $23, $E7, $E7, $6B, $B4, $17, $67, $73                        ; row 2
    .byte $73, $2F, $5C, $13, $14, $27, $E7, $E7, $25, $BF, $23, $67, $73                   ; row 3
    .byte $73, $94, $27, $E7, $E7, $E7, $25, $5C, $3F, $23, $67, $73                        ; row 4
    .byte $73, $E7, $E7, $E7, $E7, $67, $31, $44, $3B, $27, $67, $73                        ; row 5
    .byte $73, $E7, $E7, $6B, $B4, $B4, $35, $3F, $23, $E7, $73                             ; row 6
    .byte $73, $E7, $6B, $34, $37, $5C, $BF, $3D, $3F, $3F, $23, $E7, $73                   ; row 7
    .byte $73, $E7, $25, $3F, $21, $44, $2D, $39, $3E, $04, $06, $4E, $1F, $67, $73         ; row 8
    .byte $73, $E7, $25, $3F, $3C, $3F, $5C, $46, $94, $14, $27, $E7, $73                   ; row 9
    .byte $73, $E7, $26, $14, $30, $94, $27, $E7, $E7, $E7, $73                             ; row 10
    .byte $73, $E7, $E7, $E7, $E7, $E7, $E7, $E7, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World4:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $E7, $E7, $E7, $E7, $E7, $6B, $B4, $34, $73                                  ; row 2
    .byte $73, $34, $34, $20, $34, $17, $E7, $67, $6B, $34, $35, $52, $55, $52, $73         ; row 3
    .byte $73, $04, $0E, $1E, $1F, $23, $67, $6B, $34, $35, $0A, $04, $00, $04, $06, $73    ; row 4
    .byte $73, $14, $1A, $30, $3A, $32, $6B, $35, $3D, $D2, $38, $22, $12, $44, $73         ; row 5
    .byte $73, $67, $4C, $67, $26, $27, $25, $55, $3E, $04, $06, $3C, $07, $1E, $62, $73    ; row 6
    .byte $73, $6B, $1B, $17, $67, $6B, $41, $6A, $55, $D2, $48, $22, $11, $44, $73         ; row 7
    .byte $73, $25, $1F, $23, $67, $26, $27, $31, $44, $45, $10, $04, $00, $04, $06, $73    ; row 8
    .byte $73, $35, $2F, $33, $17, $E7, $25, $52, $55, $52, $13, $94, $14, $73              ; row 9
    .byte $73, $55, $AF, $33, $B4, $4A, $C4, $44, $4B, $B4, $34, $73                        ; row 10
    .byte $73, $D5, $D5, $D5, $D5, $D5, $D5, $D5, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World5:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $BF, $BF, $47, $43, $A4, $A4, $53, $D5, $0A, $73                             ; row 2
    .byte $73, $BF, $BF, $42, $A4, $A4, $24, $53, $D5, $05, $73                             ; row 3
    .byte $73, $B6, $B6, $43, $24, $50, $1F, $D1, $59, $03, $04, $00, $73                   ; row 4
    .byte $73, $A4, $A4, $50, $51, $59, $05, $D5, $55, $05, $55, $05, $73                   ; row 5
    .byte $73, $A4, $50, $51, $59, $03, $0B, $07, $04, $00, $04, $07, $55, $10, $73         ; row 6
    .byte $73, $D1, $59, $D5, $05, $D5, $D5, $D5, $55, $05, $73                             ; row 7
    .byte $73, $D5, $55, $10, $04, $07, $04, $62, $04, $06, $04, $00, $04, $07, $73         ; row 8
    .byte $73, $55, $3D, $D5, $D5, $55, $05, $55, $05, $D5, $55, $05, $73                   ; row 9
    .byte $73, $55, $3E, $04, $06, $04, $00, $04, $00, $55, $63, $04, $0A, $04, $00, $73    ; row 10
    .byte $73, $DC, $DC, $DC, $DC, $DC, $DC, $DC, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World6:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $60, $55, $33, $B4, $17, $67, $6B, $34, $17, $E7, $E7, $73                   ; row 2
    .byte $73, $6A, $D5, $D5, $33, $17, $25, $60, $23, $E7, $E7, $73                        ; row 3
    .byte $73, $00, $04, $06, $04, $06, $55, $23, $26, $14, $27, $6B, $B4, $17, $73         ; row 4
    .byte $73, $05, $38, $44, $39, $05, $55, $33, $20, $34, $20, $35, $3F, $3D, $23, $73    ; row 5
    .byte $73, $07, $3C, $62, $1E, $07, $0B, $06, $1E, $06, $1E, $06, $04, $3E, $23, $73    ; row 6
    .byte $73, $05, $48, $44, $49, $05, $02, $13, $30, $14, $30, $6A, $3F, $5C, $23, $73    ; row 7
    .byte $73, $63, $04, $06, $04, $00, $60, $33, $17, $E7, $26, $94, $27, $73              ; row 8
    .byte $73, $E0, $E0, $E0, $60, $33, $17, $E7, $E7, $67, $73                             ; row 9
    .byte $73, $3F, $E0, $E0, $E0, $60, $33, $B4, $B4, $34, $73                             ; row 10
    .byte $73, $DC, $DC, $DC, $DC, $DC, $DC, $DC, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World7:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $34, $20, $34, $17, $6B, $B4, $B4, $B4, $20, $34, $17, $73                   ; row 2
    .byte $73, $10, $4F, $00, $23, $25, $00, $04, $06, $04, $1F, $1D, $3C, $1D, $23, $73    ; row 3
    .byte $73, $1D, $3C, $05, $23, $25, $05, $9D, $1D, $05, $1D, $3C, $1F, $23, $73         ; row 4
    .byte $73, $1F, $3C, $1F, $23, $25, $10, $04, $06, $04, $00, $04, $0A, $1D, $23, $73    ; row 5
    .byte $73, $12, $11, $3B, $27, $26, $3A, $44, $22, $C4, $12, $44, $3B, $27, $73         ; row 6
    .byte $73, $4F, $1F, $23, $E7, $1F, $0B, $00, $04, $06, $4F, $62, $23, $67, $73         ; row 7
    .byte $73, $3C, $05, $23, $E7, $25, $52, $3D, $52, $5C, $3C, $05, $23, $67, $73         ; row 8
    .byte $73, $3C, $0A, $23, $E7, $25, $5C, $3E, $04, $06, $1E, $07, $23, $67, $73         ; row 9
    .byte $73, $11, $44, $4B, $B4, $4A, $C4, $C4, $11, $44, $4B, $34, $73                   ; row 10
    .byte $73, $DC, $DC, $DC, $DC, $DC, $DC, $DC, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

EndPic_World8:
    .byte $70, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $72                                       ; row 1
    .byte $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73                                       ; row 2
    .byte $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73                                       ; row 3
    .byte $73, $0F, $AA, $2A, $0F, $AA, $AA, $0F, $AA, $2A, $0F, $73                        ; row 4
    .byte $73, $2E, $D4, $54, $68, $D4, $D4, $68, $D4, $54, $2E, $73                        ; row 5
    .byte $73, $2E, $5B, $2B, $5B, $2B, $5B, $2B, $5B, $2B, $DB, $6C, $6D, $2E, $73         ; row 6
    .byte $73, $2E, $1F, $61, $69, $0B, $69, $61, $69, $61, $69, $61, $6E, $6F, $2E, $73    ; row 7
    .byte $73, $0F, $D4, $54, $0F, $D4, $D4, $0F, $D4, $54, $0F, $73                        ; row 8
    .byte $73, $9C, $9C, $9C, $9C, $9C, $9C, $9C, $73                                       ; row 9
    .byte $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73                                       ; row 10
    .byte $73, $AA, $AA, $AA, $AA, $AA, $AA, $AA, $73                                       ; row 11
    .byte $74, $F1, $F1, $F1, $F1, $F1, $F1, $F1, $75                                       ; row 12

    ; Split address, parallel tables for the starting VRAM address of the end picture for each world
EndPic_VRAMStart_H: .byte $28, $28, $28, $29, $29, $28, $28, $28    ; High
EndPic_VRAMStart_L: .byte $E3, $AD, $E9, $67, $23, $AD, $A3, $A9    ; Low

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; This table contains commands for Video_Misc_Updates2 which tells
; it how to generate certain graphical elements programatically
;
; Note: See Video_Upd_Table in PRG030 for format
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
; Remember that the left edge is typically clipped, so nothing is visible there...
Video_Upd_Table2:
    .word Graphics_Buffer       ; $00 - Graphics buffer for dynamically generated content
    .word Title_Load_Palette    ; $01 - Loads palette for title screen (and falls into Title_Checkerboard_Floor)
    .word PRG025_CA9B       ; $02 - ???
    .word Title_FadeIn_1        ; $03 - Title screen colors fade in part 1
    .word Title_FadeIn_2        ; $04 - Title screen colors fade in part 2
    .word Title_FadeIn_3        ; $05 - Title screen colors fade in part 3
    .word Title_FadeIn_4        ; $06 - Title screen colors fade in part 4
    .word Title_LoadMenu        ; $07 - Loads the 1P/2P select menu

    ; The title screen -- this is too complicated/large to load in one single buffer
    ; instance, so it is broken up across several frames in chunks.  Maybe I could
    ; explain what's being loaded a little better, but whatever :}
    .word TitleScreen_LogoLine01    ; $08 - Title Screen part 01 Title Sequence begin
    .word TitleScreen_LogoLine02    ; $09 - Title Screen part 02
    .word TitleScreen_LogoLine03    ; $0A - Title Screen part 03
    .word TitleScreen_LogoLine04    ; $0B - Title Screen part 04
    .word TitleScreen_LogoLine05    ; $0C - Title Screen part 05
    .word TitleScreen_LogoLine06    ; $0D - Title Screen part 06
    .word TitleScreen_LogoLine07    ; $0E - Title Screen part 07
    .word TitleScreen_LogoLine08    ; $0F - Title Screen part 08
    .word TitleScreen_LogoLine09    ; $10 - Title Screen part 09
    .word TitleScreen_LogoLine10    ; $11 - Title Screen part 10
    .word TitleScreen_LogoLine11    ; $12 - Title Screen part 11
    .word TitleScreen_LogoLine12    ; $13 - Title Screen part 12
    .word TitleScreen_LogoLine13    ; $14 - Title Screen part 13
    .word TitleScreen_LogoLine14    ; $15 - Title Screen part 14
    .word TitleScreen_LogoLine15    ; $16 - Title Screen part 15
    .word TitleScreen_LogoLine16    ; $17 - Title Screen part 16
    .word TitleScreen_LogoLine17    ; $18 - Title Screen part 17
    .word TitleScreen_LogoLine18    ; $19 - Title Screen part 18
    .word TitleScreen_LogoLine19    ; $1A - Title Screen part 19
    .word TitleScreen_LogoLine20    ; $1B - Title Screen part 20
    .word TitleScreen_LogoLine21    ; $1C - Title Screen part 21
    .word TitleScreen_LogoLine22    ; $1D - Title Screen part 22
    .word TitleScreen_LogoLine23    ; $1E - Title Screen part 23
    .word TitleScreen_LogoLine24    ; $1F - Title Screen part 24
    .word TitleScreen_LogoAttr1 ; $20 - Title Screen part 25
    .word TitleScreen_LogoAttr2 ; $21 - Title Screen part 26
    .word TitleScreen_DarkPal   ; $22 - Title Screen part 27 Sequence end

    .word Title_Checkerboard_Floor  ; $23 - The black & white squares at the beginning
    .word Ending_CurtainExtension   ; $24 - Slightly longer curtain in ending
    .word PRG025_CCCE       ; $25 - ???
    .word EndSeq_WorldFadeIn1   ; $26 - End pic world fade in effect part 1
    .word EndSeq_WorldFadeIn2   ; $27 - End pic world fade in effect part 2
    .word EndSeq_WorldFadeIn3   ; $28 - End pic world fade in effect part 3
    .word EndSeq_WorldFadeIn4   ; $29 - End pic world fade in effect part 4
    .word EndSeq_World1_Background1 ; $2A - Background for World 1 credits screen part 1 (images)
    .word EndSeq_World1_Background2 ; $2B - Background for World 1 credits screen part 2 (images)
    .word EndSeq_World1_Background3 ; $2C - Background for World 1 credits screen part 3 (images)
    .word EndSeq_World1_Background4 ; $2D - Background for World 1 credits screen part 4 (palette data)
    .word EndSeq_World2_Background1 ; $2E - Background for World 2 credits screen part 1 (images)
    .word EndSeq_World2_Background2 ; $2F - Background for World 2 credits screen part 2 (images)
    .word EndSeq_World2_Background3 ; $30 - Background for World 2 credits screen part 3 (images)
    .word EndSeq_World2_Background4 ; $31 - Background for World 2 credits screen part 4 (palette data)
    .word EndSeq_World3_Background1 ; $32 - Background for World 3 credits screen part 1 (images)
    .word EndSeq_World3_Background2 ; $33 - Background for World 3 credits screen part 2 (images)
    .word EndSeq_World3_Background3 ; $34 - Background for World 3 credits screen part 3 (images)
    .word EndSeq_World3_Background4 ; $35 - Background for World 3 credits screen part 4 (palette data)
    .word EndSeq_World4_Background1 ; $36 - Background for World 4 credits screen part 1 (images)
    .word EndSeq_World4_Background2 ; $37 - Background for World 4 credits screen part 2 (images)
    .word EndSeq_World4_Background3 ; $38 - Background for World 4 credits screen part 3 (palette data)
    .word EndSeq_World4_Background4 ; $39 - Background for World 4 credits screen part 4 (palette data)
    .word EndSeq_World5_Background1 ; $3A - Background for World 5 credits screen part 1 (images)
    .word EndSeq_World5_Background2 ; $3B - Background for World 5 credits screen part 2 (images)
    .word EndSeq_World5_Background3 ; $3C - Background for World 5 credits screen part 3 (images)
    .word EndSeq_World5_Background4 ; $3D - Background for World 5 credits screen part 4 (palette data)
    .word EndSeq_World6_Background1 ; $3E - Background for World 6 credits screen part 1 (images)
    .word EndSeq_World6_Background2 ; $3F - Background for World 6 credits screen part 2 (images)
    .word EndSeq_World6_Background3 ; $40 - Background for World 6 credits screen part 3 (images)
    .word EndSeq_World6_Background4 ; $41 - Background for World 6 credits screen part 4 (images)
    .word EndSeq_World6_Background5 ; $42 - Background for World 6 credits screen part 5 (images)
    .word EndSeq_World6_Background6 ; $43 - Background for World 6 credits screen part 6 (palette data)
    .word EndSeq_World7_Background1 ; $44 - Background for World 7 credits screen part 1 (images)
    .word EndSeq_World7_Background2 ; $45 - Background for World 7 credits screen part 2 (images)
    .word EndSeq_World7_Background3 ; $46 - Background for World 7 credits screen part 3 (images)
    .word EndSeq_World7_Background4 ; $47 - Background for World 7 credits screen part 4 (images)
    .word EndSeq_World7_Background5 ; $48 - Background for World 7 credits screen part 5 (palette data)
    .word EndSeq_World8_Background1 ; $49 - Background for World 8 credits screen part 1 (images)
    .word EndSeq_World8_Background2 ; $4A - Background for World 8 credits screen part 2 (images)
    .word EndSeq_World8_Background3 ; $4B - Background for World 8 credits screen part 3 (palette data)
    .word EndSeq_World8_Background4 ; $4C - Background for World 8 credits screen part 4 (palette data)
    .word EndSeq_World1Pal      ; $4D - Ending pic World 1 full palette
    .word EndSeq_World2Pal      ; $4E - Ending pic World 2 full palette
    .word EndSeq_World3Pal      ; $4F - Ending pic World 3 full palette
    .word EndSeq_World4Pal      ; $50 - Ending pic World 4 full palette
    .word EndSeq_World5Pal      ; $51 - Ending pic World 5 full palette
    .word EndSeq_World6Pal      ; $52 - Ending pic World 6 full palette
    .word EndSeq_World7Pal      ; $53 - Ending pic World 7 full palette
    .word EndSeq_World8Pal      ; $54 - Ending pic World 8 full palette
    .word EndSeq_PrincessChamber    ; $55 - Princess's chamber itself
    .word EndSeq_Fade4      ; $56 - Princess's chamber "fade in/out" effect part 4
    .word EndSeq_Fade3      ; $57 - Princess's chamber "fade in/out" effect part 3
    .word EndSeq_Fade2      ; $58 - Princess's chamber "fade in/out" effect part 2
    .word EndSeq_Fade1      ; $59 - Princess's chamber "fade in/out" effect part 1
    .word EndSeq_Fade0      ; $5A - Princess's chamber "fade out" lead (then goes back through the above)
    .word PRG025_D4B5       ; $5B - ?? Sprite palette
    .word EndSeq_CurtainFadeIn1 ; $5C - Curtain fade in effect part 1
    .word EndSeq_CurtainFadeIn2 ; $5D - Curtain fade in effect part 2
    .word EndSeq_CurtainFadeIn3 ; $5E - Curtain fade in effect part 3
    .word PRG025_D505       ; $5F -

Title_Load_Palette:
    ; This is the initial palette applied to the title screen

    DBYT $3F00
    .byte 32    ; 32 bytes to follow (32 colors)

    ; The colors!
    .byte $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F, $16, $36, $0F, $0F, $2A, $36, $0F, $0F, $27, $30, $0F, $0F, $2A, $30, $0F

    ; Falls into...

Title_Checkerboard_Floor:
    DBYT $22E0 ; Bottom of nametable
    .byte 32    ; 32 bytes to follow
    .byte $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19
    .byte $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19

    DBYT $2B00
    .byte 32    ; 32 bytes to follow
    .byte $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16
    .byte $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16, $15, $15, $16, $16

    DBYT $2B20
    .byte 32    ; 32 bytes to follow
    .byte $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7
    .byte $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7, $E6, $E6, $E7, $E7

    DBYT $2B40
    .byte 32    ; 32 bytes to follow
    .byte $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7
    .byte $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7, $F6, $F6, $F7, $F7

    DBYT $2B60
    .byte 32    ; 32 bytes to follow
    .byte $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F
    .byte $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F, $5D, $5D, $5F, $5F

    ; Terminator!
    .byte $00

TitleScreen_LogoLine01:
    DBYT $2000
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    ; Terminator
    .byte $00

TitleScreen_LogoLine02:
    DBYT $2020
    .byte $20, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
    .byte $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
    .byte $19

    ; Terminator
    .byte $00

TitleScreen_LogoLine03:
    DBYT $2040
    .byte $20, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
    .byte $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
    .byte $29

    ; Terminator
    .byte $00

TitleScreen_LogoLine04:
    DBYT $2060
    .byte VU_REPEAT | $20, $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine05:
    DBYT $2080
    .byte VU_REPEAT | $0B, $5C

    DBYT $208B
    .byte $15, $30, $31, $32, $33, $34, $35, $36, $37, $38, $39, $3A, $5C, $5C, $5C, $5C
    .byte $3B, $3C, $3D, $3E, $5C, $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine06:
    DBYT $20A0
    .byte VU_REPEAT | $0B, $5C

    DBYT $20AB
    .byte $15, $40, $41, $42, $43, $44, $45, $46, $47, $48, $49, $4A, $5C, $5C, $5C, $5C
    .byte $4B, $4C, $4D, $4E, $5C, $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine07:
    DBYT $20C0
    .byte $16, $5C, $5C, $3B, $3C, $3D, $3E, $5C, $5C, $5C, $5C, $5C, $50, $51, $52, $53
    .byte $54, $55, $56, $57, $58, $59, $5A

    DBYT $20D6
    .byte VU_REPEAT | $0A, $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine08:
    DBYT $20E0
    .byte $16, $5C, $5C, $4B, $4C, $4D, $4E, $5C, $5C, $5C, $5C, $5C, $60, $61, $62, $63
    .byte $64, $65, $66, $67, $68, $69, $6A

    DBYT $20F6
    .byte VU_REPEAT | $0A, $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine09:
    DBYT $2100
    .byte $20, $5C, $5C, $5C, $5C, $5C, $70, $71, $72, $73, $74, $75, $76, $77, $78, $79
    .byte $7A, $7B, $5C, $7D, $7E, $7F, $C0, $C1, $C2, $C3, $C4, $C5, $5C, $5C, $5C, $5C
    .byte $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine10:
    DBYT $2120
    .byte $20, $5C, $5C, $5C, $5C, $5C, $80, $81, $82, $83, $84, $85, $86, $87, $88, $89
    .byte $8A, $8B, $8C, $8D, $8E, $8F, $D0, $D1, $D2, $D3, $D4, $D5, $5C, $5C, $5C, $5C
    .byte $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine11:
    DBYT $2140
    .byte $20, $5C, $5C, $5C, $5C, $5C, $90, $91, $92, $93, $94, $95, $96, $97, $98, $99
    .byte $9A, $9B, $9C, $9D, $9E, $9F, $E0, $E1, $E2, $E3, $E4, $E5, $5C, $5C, $5C, $5C
    .byte $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine12:
    DBYT $2160
    .byte $20, $5C, $5C, $5C, $5C, $5C, $A0, $A1, $A2, $A3, $A4, $A5, $A6, $A7, $A8, $A9
    .byte $AA, $AB, $AC, $AD, $AE, $AF, $F0, $F1, $F2, $F3, $F4, $F5, $5C, $5C, $5C, $5C
    .byte $5C

    ; Terminator
    .byte $00

TitleScreen_LogoLine13:
    DBYT $2180
    .byte $20, $5B, $6B, $5C, $5C, $5C, $B0, $B1, $B2, $B3, $B4, $B5, $B6, $B7, $B8, $B9
    .byte $BA, $BB, $BC, $BD, $BE, $BF, $C6, $C7, $C8, $D6, $D7, $D8, $E8, $04, $05, $06
    .byte $07

    ; Terminator
    .byte $00

TitleScreen_LogoLine14:
    DBYT $21A0
    .byte VU_REPEAT | $0E, $5C

    DBYT $21AE
    .byte $12, $C9, $CA, $CB, $CC, $CD, $CE, $CF, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $14
    .byte $21, $21, $17

    ; Terminator
    .byte $00

TitleScreen_LogoLine15:
    DBYT $21C0
    .byte VU_REPEAT | $0E, $5C

    DBYT $21CE
    .byte $12, $D9, $DA, $DB, $DC, $DD, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20
    .byte $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine16:
    DBYT $21E0
    .byte VU_REPEAT | $0E, $5C

    DBYT $21EE
    .byte $12, $E9, $EA, $EB, $EC, $ED, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20
    .byte $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine17:
    DBYT $2200
    .byte $20, $04, $05, $06, $07, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $F9
    .byte $FA, $FB, $FF, $FD, $FE, $5C, $5C, $5C, $5C, $5C, $5C, $04, $05, $02, $03, $21
    .byte $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine18:
    DBYT $2220
    .byte $20, $14, $21, $21, $22, $24, $25, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $6C
    .byte $6D, $6E, $6F, $DE, $DF, $5C, $5C, $5C, $5C, $5C, $5C, $14, $21, $21, $13, $21
    .byte $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine19:
    DBYT $2240
    .byte $20, $20, $21, $21, $23, $5F, $11, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C
    .byte $5C, $EE, $EF, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $5C, $20, $21, $21, $21, $21
    .byte $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine20:
    DBYT $2260
    .byte $06, $20, $21, $21, $23, $5F, $5F

    DBYT $2266
    .byte VU_REPEAT | $14, $5C

    DBYT $227A
    .byte $06, $20, $21, $21, $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine21:
    DBYT $2280
    .byte $06, $20, $21, $00, $01, $26, $27

    DBYT $2286
    .byte VU_REPEAT | $14, $5C

    DBYT $229A
    .byte $06, $20, $21, $21, $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine22:
    DBYT $22A0
    .byte $08, $20, $21, $10, $21, $21, $22, $24, $25

    DBYT $22A8
    .byte VU_REPEAT | $12, $5C

    DBYT $22BA
    .byte $06, $20, $21, $21, $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine23:
    DBYT $22C0
    .byte $08, $20, $21, $21, $21, $21, $23, $5F, $11

    DBYT $22C8
    .byte VU_REPEAT | $10, $5C

    DBYT $22D8
    .byte $08, $04, $05, $02, $03, $21, $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoLine24:
    DBYT $22E0
    .byte $08, $20, $21, $21, $21, $21, $23, $5F, $5F

    DBYT $22E8
    .byte VU_REPEAT | $10, $5C

    DBYT $22F8
    .byte $08, $14, $21, $21, $13, $21, $21, $21, $23

    ; Terminator
    .byte $00

TitleScreen_LogoAttr1:
    DBYT $23C0
    .byte $20, $F0, $F0, $F0, $F0, $F0, $F0, $F0, $F0, $2A, $8A, $66, $55, $55, $99, $A2
    .byte $A8, $AA, $55, $55, $55, $55, $55, $55, $A9, $A8, $A6, $A5, $ED, $77, $B5, $A5
    .byte $AA

    ; Terminator
    .byte $00

TitleScreen_LogoAttr2:
    DBYT $23E0
    .byte $20, $AA, $AA, $0A, $0E, $0F, $0B, $AA, $AA, $AA, $AA, $22, $00, $00, $00, $AA
    .byte $AA, $00, $00, $00, $00, $00, $00, $00, $00, $0A, $0A, $0A, $0A, $0A, $0A, $0A
    .byte $0A

    ; Terminator
    .byte $00

TitleScreen_DarkPal:
    DBYT $3F00
    .byte $10, $0F, $0F, $30, $0F, $0F, $0F, $21, $02, $0F, $0F, $0F, $0F, $0F, $0F, $27
    .byte $02

    ; Terminator
    .byte $00

PRG025_CA9B:
    DBYT $3F00
    .byte 16    ; 16 bytes (colors) to follow...
    .byte $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F

    ; Terminator
    .byte $00

Title_FadeIn_1:
    DBYT $3F00
    .byte 16    ; 16 bytes (colors) to follow...
    .byte $07, $0F, $00, $06, $07, $0F, $01, $02, $07, $0F, $0A, $0A, $07, $0F, $07, $02
    .byte $00   ; Terminator

Title_FadeIn_2:
    DBYT $3F00
    .byte 16    ; 16 bytes (colors) to follow...
    .byte $17, $0F, $10, $16, $17, $0F, $11, $02, $17, $0F, $1A, $1A, $17, $0F, $17, $02
    .byte $00   ; Terminator

Title_FadeIn_3:
    DBYT $3F00
    .byte 16    ; 16 bytes (colors) to follow...
    .byte $27, $0F, $20, $16, $27, $0F, $21, $02, $27, $0F, $2A, $1A, $27, $0F, $27, $02
    .byte $00   ; Terminator

Title_FadeIn_4:
    DBYT $3F00
    .byte 16    ; 16 bytes (colors) to follow...
    .byte $37, $0F, $30, $16, $37, $0F, $21, $02, $37, $0F, $2A, $1A, $37, $0F, $27, $02
    .byte $00   ; Terminator

Title_LoadMenu:

    ; 1 PLAYER GAME
    DBYT $226A
    .byte 13    ; 13 bytes to follow
    .byte $0E, $5C, $0A, $0B, $0C, $1A, $1B, $0D, $5C, $1C, $0C, $1D, $1B

    ; 2 PLAYER GAME
    DBYT $22AA
    .byte 13    ; 13 bytes to follow
    .byte $1E, $5C, $0A, $0B, $0C, $1A, $1B, $0D, $5C, $1C, $0C, $1D, $1B

    ; C 1988 Nintendo
    DBYT $22EA
    .byte 13    ; 13 bytes to follow
    .byte $3F, $5C, $0E, $0F, $1F, $1F, $5C, $2A, $2B, $2C, $2D, $2E, $2F

    .byte $00   ; Terminator

Ending_CurtainExtension:
    DBYT $22E0
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2300
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2320
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2340
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2360
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2380
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $23A0
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2800
    .byte $20, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08, $09, $08
    .byte $09

    DBYT $2820
    .byte $20, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
    .byte $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18, $19, $18
    .byte $19

    DBYT $2840
    .byte $20, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
    .byte $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28, $29, $28
    .byte $29

    DBYT $23C0
    .byte VU_REPEAT | $20, $00

    DBYT $23E0
    .byte VU_REPEAT | $10, $00

    DBYT $23F0
    .byte VU_REPEAT | $10, $00

    DBYT $2BC0
    .byte VU_REPEAT | $08, $A0

    DBYT $2BC8
    .byte VU_REPEAT | $08, $AA

    DBYT $2BD0
    .byte VU_REPEAT | $10, $AA

    DBYT $2BE0
    .byte VU_REPEAT | $10, $AA

    DBYT $3F00
    .byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00

PRG025_CCCE:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00

EndSeq_WorldFadeIn1:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $0F, $0F, $00, $0F, $0F, $00, $0F, $0F, $0F, $00
    .byte $00, $0F, $0F, $0F, $00, $0F, $00, $0F, $0F, $0F, $00, $0F, $0F, $0F, $00, $0F
    .byte $0F

    ; Terminator
    .byte $00

EndSeq_WorldFadeIn2:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $0F, $00, $10, $0F, $00, $10, $00, $0F, $00, $10
    .byte $10, $0F, $00, $00, $10, $0F, $10, $00, $00, $0F, $10, $00, $00, $0F, $10, $00
    .byte $00

    ; Terminator
    .byte $00

EndSeq_WorldFadeIn3:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $00, $10, $30, $0F, $10, $30, $10, $0F, $10, $30
    .byte $30, $0F, $10, $10, $30, $0F, $30, $10, $10, $0F, $30, $10, $10, $0F, $30, $10
    .byte $10

    ; Terminator
    .byte $00

EndSeq_WorldFadeIn4:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $27, $2A, $36, $0F, $3C, $30, $37, $0F, $21, $2A
    .byte $36, $0F, $10, $36, $0F, $0F, $25, $36, $0F, $0F, $29, $36, $0F, $0F, $29, $36
    .byte $0F

    ; Terminator
    .byte $00

EndSeq_World1_Background1:
PRG025_CD82:    
    ; See Video_Upd_Table in PRG30.asm for format

    DBYT $28F4
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $77 ; WORLD 1 Text

    DBYT $2974
    .byte $0A
    .byte $E8, $EF, $E0, $F8, $F8, $5C, $F1, $E0, $F3, $E3  ; GRASS LAND Text

    DBYT $2A5C
    .byte $04
    .byte $D0, $D1, $D2, $D3    ; Part of right hand bush

    DBYT $2A7C
    .byte VU_VERT | $02
    .byte $D4, $D6  ;Part of right hand bush

    .byte TERMINATOR

EndSeq_World1_Background2:
PRG025_CDA6:
    
    DBYT $2A7F 
    .byte VU_VERT | $05 
    .byte $D5, $D7, $D7, $D7, $D7   ;Part of right hand bush

    DBYT $2ABA
    .byte $04
    .byte $D0, $D1, $D2, $D3    ;Part of right hand bush

    DBYT $2ADA
    .byte VU_VERT | $02
    .byte $D4, $D6  ;Part of right hand bush

    .byte TERMINATOR


EndSeq_World1_Background3:
PRG025_CDBB:
    
    DBYT $2A80
    .byte $03
    .byte $D1, $D2, $D3   

    DBYT $2AA2
    .byte $01
    .byte $D5   ;Part of left hand bush
    
    DBYT $2AC1
    .byte $04
    .byte $D0, $D1, $D2, $D3    ;Part of left hand bush
    
    DBYT $2AE4
    .byte $01
    .byte $D5   ;Part of left hand bush

    .byte TERMINATOR

EndSeq_World1_Background4:
PRG025_CDD1:
        
    DBYT $2BD1
    .byte $04
    .byte $55, $55, $55, $99    ; Background palette data for W1 Map (upper)

    DBYT $2BD9
    .byte $04
    .byte $55, $55, $7F, $BB    ; Background palette data for W1 Map (middle)
    
    DBYT $2BE1
    .byte $04
    .byte $A5, $A5, $AF, $AB    ; Background palette data for W1 Map (lower)

    .byte TERMINATOR

EndSeq_World2_Background1:
PRG025_CDE7:

    DBYT $28E3
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $78 ; WORLD 2 text
    
    DBYT $2924
    .byte $06
    .byte $E3, $E4, $F8, $E4, $EF, $F9  ; DESERT text
    
    DBYT $2967
    .byte $04
    .byte $F1, $E0, $F3, $E3    ; LAND text
    
    .byte TERMINATOR

EndSeq_World2_Background2:
PRG025_CE02:
    DBYT $2A65
    .byte $01
    .byte $58   ; Pyramid top
    
    DBYT $2A82
    .byte $05
    .byte $58, $5C, $57, $5C, $56   ; Pyramid row 2

    DBYT $2AA1
    .byte $07
    .byte $57, $5C, $5A, $5C, $5C, $5C, $56 ; Pyramid row 3

    .byte TERMINATOR        

EndSeq_World2_Background3:
PRG025_CE19:
    DBYT $2AC0
    .byte $03
    .byte $57, $5C, $57 ; Pyramid bottom row
        
    DBYT $2AC8
    .byte $01
    .byte $56 ; Pyramid bottom row
    
    DBYT $2AE1
    .byte $01
    .byte $57 ; Pyramid bottom row
    
    DBYT $2AE9
    .byte $01
    .byte $56 ; Pyramid bottom row
    
    .byte TERMINATOR
    .byte TERMINATOR

EndSeq_World2_Background4:
PRG025_CE2D:
    DBYT $2BCB
    .byte $04
    .byte $EA, $5A, $5A, $5A    ; Background palette data for world map
    
    DBYT $2BD3
    .byte $04
    .byte $66, $55, $55, $55    ; Background palette data for world map
    
    DBYT $2BDB
    .byte $04
    .byte $66, $55, $55, $55    ; Background palette data for world map
    
    .byte TERMINATOR


EndSeq_World3_Background1:
PRG025_CE43:

    DBYT $29A2
    .byte $05
    .byte $DE, $F4, $EF, $F1, $E3 ; "World" text

    DBYT $29E4
    .byte $01
    .byte $79   ; "3" in World 3 text

    DBYT $2A9A
    .byte $04
    .byte $CA, $CB, $CC, $CD    ; Top of the pipe
    
    .byte TERMINATOR

EndSeq_World3_Background2:
PRG025_CE57:
    DBYT $2ABA
    .byte $04
    .byte $DA, $DB, $DC, $DD    ; Middle top of pipe
    
    DBYT $2ADA
    .byte $04
    .byte $CE, $CF, $5C, $DF ; Middle bottom of pipe
    
    DBYT $2AFA
    .byte $04
    .byte $CE, $CF, $5C, $DF    ; Bottom of pipe

    .byte TERMINATOR

EndSeq_World3_Background3:
PRG025_CE6D:
    DBYT $2A89
    .byte $0A
    .byte $DE, $E0, $F9, $E4, $EF, $5C, $F1, $E0, $F3, $E3  ; "Water Land" text

    .byte TERMINATOR

EndSeq_World3_Background4:
PRG025_CE7B:
    DBYT $2BD2
    .byte $04
    .byte $E6, $FF, $FF, $FF    ; Background palette data for world map
    
    DBYT $2BDA
    .byte $04
    .byte $EE, $FF, $FF, $FF    ; Background palette data for world map
    
    DBYT $2BE2
    .byte $04
    .byte $AE, $AF, $AF, $AF    ; Background palette data for world map
    
    .byte TERMINATOR

EndSeq_World4_Background1:
PRG025_CE91:

    DBYT $2978
    .byte $05
    .byte $DE, $F4, $EF, $F1, $E3   ; World

    DBYT $29BA
    .byte $01
    .byte $7A                       ; 4

    .byte TERMINATOR   


EndSeq_World4_Background2:
PRG025_CE9E:
    DBYT $2A19
    .byte $05
    .byte $E8, $EA, $E0, $F3, $F9   ; Giant
    
    DBYT $2A59
    .byte $04
    .byte $F1, $E0, $F3, $E3    ; Land
    
    .byte TERMINATOR

EndSeq_World4_Background3:
PRG025_CEAE:
    DBYT $2BDA
    .byte $04
    .byte $FF, $FF, $FF, $BB    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World4_Background4:
PRG025_CEB6:
    DBYT $2BE2
    .byte $04
    .byte $FF, $FF, $FF, $BB    ; Background palette for world map
    
    DBYT $2BEA
    .byte $04
    .byte $AF, $AF, $AF, $AB    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World5_Background1:
PRG025_CEC5:
    DBYT $28F6
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $7B ; "World 5"
    
    DBYT $2936
    .byte $08
    .byte $F8, $F0, $FE, $5C, $F1, $E0, $F3, $E3 ; "Sky Land"
    
    DBYT $28D0
    .byte $04
    .byte $C0, $C1, $C2, $C3 ; - top half of top left cloud
     
    .byte TERMINATOR

EndSeq_World5_Background2:
PRG025_CEE2:
    DBYT $28F0
    .byte $04
    .byte $C4, $C5, $C6, $C7 ; - bottom half of top left cloud
    
    DBYT $2999
    .byte $04
    .byte $C0, $C1, $C2, $C3 ; - top half of bottom right cloud
    
    DBYT $29B9
    .byte $04
    .byte $C4, $C5, $C6, $C7 ; - bottom half of bottom right cloud
    
    DBYT $2AF9
    .byte $04
    .byte $D0, $D1, $D2, $D3 ; - mound under statue Mario
    
    .byte TERMINATOR

EndSeq_World5_Background3:
PRG025_CEFF:

    DBYT $28F6
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $7B ; - "World 5" - repeated from above
    
    .byte TERMINATOR

EndSeq_World5_Background4:
PRG025_CF0A:
    DBYT $2BD1
    .byte $04
    .byte $5A, $FA, $FA, $9A    ; Background palette for world map
    
    DBYT $2BD9
    .byte $04
    .byte $FF, $7F, $5F, $99    ; Background palette for world map
    
    DBYT $2BE1
    .byte $04 
    .byte $55, $55, $55, $99    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World6_Background1:
PRG025_CF20:
    DBYT $28E3 
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $7C ; - World 6

    DBYT $2A51
    .byte $08
    .byte $EA, $E2, $E4, $5C, $F1, $E0, $F3, $E3 ; - Ice Land
    
    DBYT $2A20
    .byte $0A
    .byte $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D ; - top of the top row of block pile
    
    .byte TERMINATOR

EndSeq_World6_Background2:
PRG025_CF43:
    DBYT $2A40
    .byte $0A
    .byte $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D ; - bottom of the top row of block pile
    
    DBYT $2A60
    .byte $0A
    .byte $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D ; - top of the middle row of block pile
    
    DBYT $2A80
    .byte $0A
    .byte $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D ; - bottom of the middle row of block pile

    .byte TERMINATOR

EndSeq_World6_Background3:
PRG025_CF6B:
    DBYT $2AA0
    .byte $0C
    .byte $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D, $01, $0D ; top of bottom row of block pile

    DBYT $2AC0
    .byte $0C
    .byte $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D, $40, $4D ; bottom of bottom row of block pile
    
    .byte TERMINATOR

EndSeq_World6_Background4:
PRG025_CF8A:   
    DBYT $2AE0
    .byte $10
    .byte $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9 ; part of line under blocks pile
    
    .byte TERMINATOR

EndSeq_World6_Background5:
PRG025_CF9E:
    DBYT $2AF0
    .byte $10
    .byte $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9, $D8, $C9 ; rest of line under block pile
    
    .byte TERMINATOR

EndSeq_World6_Background6:
PRG025_CFB2:
    DBYT $2BCB
    .byte $04
    .byte $EA, $FA, $FA, $FA    ; Background palette for world map
    
    DBYT $2BD3
    .byte $04
    .byte $EE, $7F, $FF, $FF    ; Background palette for world map
    
    DBYT $2BDB
    .byte $04
    .byte $EE, $FF, $FF, $FF    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World7_Background1:
PRG025_CFC8:
    DBYT $2A43
    .byte $07
    .byte $DE, $F4, $EF, $F1, $E3, $5C, $7D ; "World 7"
    
    DBYT $2A84
    .byte $09
    .byte $F5, $EA, $F5, $E4, $5C, $F1, $E0, $F3, $E3 ; "Pipe Land"
    
    DBYT $299A
    .byte $04
    .byte $CA, $CB, $CC, $CD ; - Top of rim of tall right pipe
    
    DBYT $29BA
    .byte $04
    .byte $DA, $DB, $DC, $DD ; - Bottom of rim of tall right pipe

    .byte TERMINATOR

EndSeq_World7_Background2:
PRG025_CFED:
    DBYT $29DA
    .byte VU_VERT | VU_REPEAT | $0A ; Left wall of tall right pipe
    .byte $CE
    
    DBYT $29DB
    .byte VU_VERT | VU_REPEAT | $0A
    .byte $CF ; Interior lines of tall right pipe
    
    .byte TERMINATOR

EndSeq_World7_Background3:
PRG025_CFF6:
    .DBYT $29DD
    .byte VU_VERT | VU_REPEAT | $0A
    .byte $DF ; Right wall of tall right pipe

    DBYT $2A74
    .byte $04
    .byte $CA, $CB, $CC, $CD ; Top of rim of low left pipe
    
    DBYT $2A94
    .byte $04
    .byte $DA, $DB, $DC, $DD ; Bottom of rim of low left pipe
    
    .byte TERMINATOR

EndSeq_World7_Background4:
PRG025_D009:
    DBYT $2AB4
    .byte $04
    .byte $CE, $CF, $5C, $DF ; top row of pipe shaft for low left pipe
    
    DBYT $2AD4
    .byte $04
    .byte $CE, $CF, $5C, $DF ; middle row of pipe shaft for low left pipe
    
    DBYT $2AF4
    .byte $04
    .byte $CE, $CF, $5C, $DF ; bottom row of pipe shaft for low left pipe

    .byte TERMINATOR

EndSeq_World7_Background5:
PRG025_D01F:
    DBYT $2BC9
    .byte $04
    .byte $FA, $FA, $FA, $BA    ; Background palette for world map
    
    DBYT $2BD1
    .byte $04
    .byte $FF, $FF, $FF, $BB    ; Background palette for world map
    
    DBYT $2BD9
    .byte $04
    .byte $FF, $FF, $FF, $BB    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World8_Background1:
PRG025_D035:
    DBYT $2963
    .byte $04
    .byte $E3, $E0, $EF, $F0    ; "Dark"
    
    DBYT $29A3
    .byte $04
    .byte $F1, $E0, $F3, $E3    ; "Land"
    
    .byte TERMINATOR

EndSeq_World8_Background2:
PRG025_D044:
    DBYT $297A
    .byte $05
    .byte $DE, $F4, $EF, $F1, $E3   ; "World"
    
    DBYT $299C
    .byte $01
    .byte $7E                   ; "8"
    
    .byte TERMINATOR

EndSeq_World8_Background3:
PRG025_D051:
    DBYT $2BCA
    .byte $04
    .byte $6A, $5A, $5A, $5A    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World8_Background4:
PRG025_D059:
    DBYT $2BD2
    .byte $04
    .byte $66, $55, $55, $55    ; Background palette for world map
    
    DBYT $2BDA
    .byte $04
    .byte $66, $55, $55, $55    ; Background palette for world map
    
    .byte TERMINATOR

EndSeq_World1Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_World2Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $2A, $0F, $0F, $30
    .byte $2A

    ; Terminator
    .byte $00

EndSeq_World3Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $37, $0F, $2A, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_World4Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $3A, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30, $16, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_World5Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $30, $0F, $2C, $30, $37, $0F, $2C, $30
    .byte $30, $0F, $17, $36, $0F, $0F, $0F, $00, $10, $0F, $0F, $30, $26, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_World6Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $30, $0F, $2C, $30, $37, $0F, $2C, $30
    .byte $30, $0F, $16, $36, $0F, $0F, $0F, $30, $16, $0F, $0F, $30, $2A, $0F, $0F, $30
    .byte $2A

    ; Terminator
    .byte $00

EndSeq_World7Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $3A, $0F, $30, $36, $0F, $0F, $0F, $21, $2A, $0F, $0F, $30, $16, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_World8Pal:
        DBYT $3F00
    .byte $20, $0F, $0F, $30, $16, $0F, $17, $2A, $37, $0F, $2C, $30, $37, $0F, $2C, $2A
    .byte $37, $0F, $16, $36, $0F, $0F, $0F, $30, $0B, $0F, $0F, $30, $16, $0F, $0F, $30
    .byte $16

    ; Terminator
    .byte $00

EndSeq_PrincessChamber:
    DBYT $3F00
    .byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    DBYT $2BC0
    .byte $30, $00, $00, $00, $00, $00, $00, $00, $00, $00, $F0, $7F, $5F, $5F, $DF, $F0
    .byte $00, $FC, $57, $55, $55, $55, $55, $5D, $F3, $77, $55, $55, $55, $55, $55, $55
    .byte $DD, $77, $55, $55, $55, $55, $55, $55, $DD, $77, $55, $55, $55, $55, $55, $55
    .byte $DD

    DBYT $2888
    .byte $10, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A, $68, $6A

    DBYT $28A8
    .byte $10, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B, $69, $6B

    DBYT $28C4
    .byte $18, $68, $6A, $68, $6A, $68, $6A, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF, $FF
    .byte $FF, $FF, $FF, $68, $6A, $68, $6A, $68, $6A

    DBYT $28E4
    .byte $18, $69, $6B, $69, $6B, $69, $6B, $99, $99, $99, $99, $99, $99, $99, $99, $99
    .byte $99, $99, $99, $69, $6B, $69, $6B, $69, $6B

    DBYT $2902
    .byte $1C, $68, $6A, $68, $6A, $FF, $FF, $FF, $FF, $99, $99, $99, $99, $99, $99, $99
    .byte $99, $99, $99, $99, $99, $FF, $FF, $FF, $FF, $68, $6A, $68, $6A

    DBYT $2922
    .byte $1C, $69, $6B, $69, $6B, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99
    .byte $99, $99, $99, $99, $99, $99, $99, $99, $99, $69, $6B, $69, $6B

    DBYT $2940
    .byte $20, $68, $6A, $68, $6A, $FF, $FF, $99, $99, $99, $99, $99, $99, $99, $99, $99
    .byte $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $99, $FF, $FF, $68, $6A, $68
    .byte $6A

    DBYT $2960
    .byte $04, $69, $6B, $69, $6B

    DBYT $2964
    .byte VU_REPEAT | $18, $99

    DBYT $297C
    .byte $04, $69, $6B, $69, $6B

    DBYT $2980
    .byte $04, $68, $6A, $FF, $FF

    DBYT $2984
    .byte VU_REPEAT | $18, $99

    DBYT $299C
    .byte $04, $FF, $FF, $68, $6A

    DBYT $29A0
    .byte $02, $69, $6B

    DBYT $29A2
    .byte VU_REPEAT | $1B, $99

    DBYT $29BD
    .byte $03, $FF, $69, $6B

    DBYT $29C0
    .byte $02, $68, $6A

    DBYT $29C2
    .byte VU_REPEAT | $1B, $99

    DBYT $29DD
    .byte $03, $FF, $68, $6A

    DBYT $29E0
    .byte $02, $69, $6B

    DBYT $29E2
    .byte VU_REPEAT | $1B, $99

    DBYT $29FD
    .byte $03, $FF, $69, $6B

    DBYT $2A00
    .byte $02, $68, $6A

    DBYT $2A02

    .byte VU_REPEAT | $1B, $99

    DBYT $2A1D
    .byte $03, $FF, $68, $6A

    DBYT $2A20
    .byte $02, $69, $6B

    DBYT $2A22
    .byte VU_REPEAT | $1B, $99

    DBYT $2A3D
    .byte $03, $FF, $69, $6B

    DBYT $2A40
    .byte $02, $68, $6A

    DBYT $2A42
    .byte VU_REPEAT | $1B, $99

    DBYT $2A5D
    .byte $03, $FF, $68, $6A

    DBYT $2A60
    .byte $02, $69, $6B

    DBYT $2A62
    .byte VU_REPEAT | $1B, $99

    DBYT $2A7D
    .byte $03, $FF, $69, $6B

    DBYT $2A80
    .byte $02, $68, $6A

    DBYT $2A82
    .byte VU_REPEAT | $1B, $99

    DBYT $2A84
    .byte VU_REPEAT | $02, $FF

    DBYT $2A9D
    .byte $03, $FF, $68, $6A

    DBYT $2AA0
    .byte $02, $69, $6B

    DBYT $2AA2
    .byte VU_REPEAT | $1B, $99

    DBYT $2AA4
    .byte VU_REPEAT | $02, $FF

    DBYT $2ABD
    .byte $03, $FF, $69, $6B

    DBYT $2AC0
    .byte $02, $68, $6A

    DBYT $2AC2
    .byte VU_REPEAT | $1B, $99

    DBYT $2AC4
    .byte VU_REPEAT | $02, $FF

    DBYT $2ADD
    .byte $03, $FF, $68, $6A

    DBYT $2AE0
    .byte $02, $69, $6B

    DBYT $2AE2
    .byte VU_REPEAT | $1B, $99

    DBYT $2AE4
    .byte VU_REPEAT | $02, $FF

    DBYT $2AFD
    .byte $03, $FF, $69, $6B

    DBYT $2B00
    .byte $20, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63
    .byte $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63, $63, $62, $62, $63
    .byte $63

    DBYT $2B20
    .byte $20, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC
    .byte $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC
    .byte $FC

    DBYT $2B40
    .byte $20, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
    .byte $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
    .byte $FD

    DBYT $2B60
    .byte $20, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
    .byte $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD, $FD, $FC, $FC, $FD
    .byte $FD

    ; Terminator
    .byte $00

EndSeq_Fade4:
    DBYT $3F00
    .byte $20, $0F, $0F, $30, $3C, $0F, $0C, $1C, $3B, $0F, $27, $30, $17, $0F, $12, $31
    .byte $21, $0F, $16, $36, $0F, $0F, $36, $25, $07, $0F, $2A, $36, $0F, $0F, $00, $00, $00

    ; Terminator
    .byte $00

EndSeq_Fade3:
    DBYT $3F00
    .byte $20, $0F, $0F, $20, $2C, $0F, $0F, $0C, $2B, $0F, $17, $20, $07, $0F, $02, $21
    .byte $11, $0F, $06, $26, $0F, $0F, $26, $15, $0F, $0F, $1A, $26, $0F, $0F, $0F, $0F, $0F

    ; Terminator
    .byte $00

EndSeq_Fade2:
    DBYT $3F00
    .byte $20, $0F, $0F, $10, $1C, $0F, $0F, $0F, $1B, $0F, $07, $10, $0F, $0F, $0F, $11
    .byte $01, $0F, $0F, $16, $0F, $0F, $16, $05, $0F, $0F, $0A, $16, $0F, $0F, $0F, $0F, $0F

    ; Terminator
    .byte $00

EndSeq_Fade1:
    DBYT $3F00
    .byte $20, $0F, $0F, $00, $0C, $0F, $0F, $0F, $0B, $0F, $0F, $00, $0F, $0F, $0F, $01
    .byte $0F, $0F, $0F, $06, $0F, $0F, $06, $0F, $0F, $0F, $0F, $06, $0F, $0F, $0F, $0F, $0F

    ; Terminator
    .byte $00

EndSeq_Fade0:
    DBYT $3F00
    .byte $20, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F

    ; Terminator
    .byte $00

PRG025_D4B5:
        DBYT $3F10
    .byte $10, $0F, $21, $30, $0F, $0F, $11, $10, $0F, $0F, $12, $00, $0F, $0F, $0C, $0F
    .byte $0F

    ; Terminator
    .byte $00

EndSeq_CurtainFadeIn1:
        DBYT $3F00
    .byte $10, $0F, $0F, $00, $06, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00


EndSeq_CurtainFadeIn2:
        DBYT $3F00
    .byte $10, $0F, $0F, $10, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00


EndSeq_CurtainFadeIn3:
       DBYT $3F00
    .byte $10, $0F, $0F, $20, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00

PRG025_D505:
        DBYT $3F00
    .byte $10, $0F, $0F, $30, $16, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F, $0F
    .byte $0F

    ; Terminator
    .byte $00


; Rest of ROM bank was empty

